### ISSUE TITLE
Проблема с получением секретов Lockbox

### ISSUE THREAD

**Issue by Bazarovinc** [yc-actions/yc-sls-container-deploy#783]
```yml
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        env:
          CR_REGISTRY: ${{ secrets.YC_REGISTRY_ID }}
          CR_REPOSITORY: <repo_name>
          IMAGE_TAG: ${{ steps.version.outputs.version }}
          ACTIONS_STEP_DEBUG: true
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: <container_name>
          folder-id:  ${{ secrets.YC_SLS_FOLDER_ID }}
          revision-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          revision-env: |
            WEBHOOK=${{ secrets.TG_BOT_WEBHOOK }}
          revision-secrets: |
            token=${{ secrets.YC_LOCKBOX_SECRET_ID }}/${{ secrets.YC_LOCKBOX_SECRET_VERSION_ID }}/${{ secrets.YC_LOCKBOX_SECRET_KEY }}
          revision-cores: 1
          revision-memory: 768Mb
          revision-core-fraction: 5
          revision-concurrency: 1
          revision-image-url: cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          revision-execution-timeout: 180
```
При подобном сценарии использования шаблона, когда задается значение `revision-secrets`
Возникает следующая ошибка

```
Run yc-actions/yc-sls-container-deploy@v2
  
start
Secrets string: "token=***/***/***"
SecretsObject: "[***"environmentVariable":"token","id":"***","versionId":"***","key":"***"***]"
Folder ID: ***, container name:  <container_name>
Container with name: <container_name> already exists and has id: <revision_id>
Creating new revision.
Error: ApiError: /yandex.cloud.serverless.containers.v1.ContainerService/DeployRevision PERMISSION_DENIED: Permission denied
Error: /yandex.cloud.serverless.containers.v1.ContainerService/DeployRevision PERMISSION_DENIED: Permission denied
```
Сервисному акаунту выданы доступы:
`container-registry.images.pusher`
`lockbox.payloadViewer`
`serverless-containers.admin`
`iam.serviceAccounts.user`

Так же заведена федерация по данной [инструкции](https://yandex.cloud/ru/docs/tutorials/security/wlif-github-integration) и протестировано получение секретов
